export const domainEventTypes = [
  "INCIDENT_REPORTED",
  "HELP_REQUEST_CREATED",
  "HELP_REQUEST_UPDATED",
  "HELP_REQUEST_NEED_ADDED",
  "RESOURCE_OFFERED",
  "VOLUNTEER_REGISTERED",
  "VOLUNTEER_AVAILABILITY_UPDATED",
  "MATCH_SEARCH_STARTED",
  "MISSION_CREATED",
  "MISSION_ASSIGNMENT_CREATED",
  "MISSION_STATUS_CHANGED",
  "OUTBOX_EVENT_PUBLISHED",
  "NODE_HANDSHAKE_COMPLETED"
] as const;

export type DomainEventType = (typeof domainEventTypes)[number];
